version: "3.9"

services:
  openmohaa:
    image: ghcr.io/mmbesar/openmohaa-container:latest-arm64
    container_name: openmohaa
    network_mode: "host"
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      GAME_PORT: 12203
      GAMESPY_PORT: 12300
    volumes:
      - ${CONTAINER_DIR}/openmohaa/mohaa:/usr/local/share/mohaa
    command:
      [
        # "+set", "fs_homepath", "home",
        "+set", "com_target_game", "0",
        "+set", "sv_maxclients", "16",
        "+exec", "server.cfg"
      ]
