version: "3.9"

services:
  openmohaa:
    image: ghcr.io/mmbesar/openmohaa-container:latest-arm64
    container_name: openmohaa
    network_mode: "host"
    restart: unless-stopped
    environment:
      GAME_PORT: 12203
      GAMESPY_PORT: 12300
      PUID: ${PUID}
      PGID: ${PGID}

    volumes:
      - ${CONTAINER_DIR}/openmohaa/mohaa:/usr/local/share/mohaa

    command: ["+set", "com_target_game", "0", "+exec", "server.cfg"]
