version: "3.9"

services:
  server:
    image: ghcr.io/YOUR_USERNAME/openmohaa:latest
    container_name: openmohaa-server
    restart: unless-stopped
    ports:
      - "12203:12203/udp"
      - "12204:12204/udp"
    volumes:
      - ./assets:/opt/openmohaa/main:ro
      - ./config:/opt/openmohaa/config
    command: ["+set", "fs_homepath", "/opt/openmohaa", "+set", "exec", "server.cfg"]
