name: Build & Push Multi-Arch

on:
  push:
    branches: [main, master]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        platform: [linux/amd64,linux/arm64,linux/arm/v7]

    steps:
      - uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/amd64,linux/arm64,linux/arm/v7"

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: "linux/amd64,linux/arm64,linux/arm/v7"
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner | toLower }}/openmohaa-container:latest
            ghcr.io/${{ github.repository_owner | toLower }}/openmohaa-container:${{ github.ref_name }}

      - name: GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
