name: Build & Push Multi-Arch

on:
  push:
    branches: [main, master]
    tags: ['v*']
    paths-ignore:
      - '**.md'
      - 'README.md'
      - '**.txt'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
          - { platform: linux/amd64, base: amd64, tag: amd64 }
          - { platform: linux/arm64, base: arm64, tag: arm64 }
          - { platform: linux/arm/v7, base: armhf, tag: armhf }

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Normalize repo owner lowercase
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push ${{ matrix.arch.tag }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: ${{ matrix.arch.platform }}
          build-args: |
            TARGETPLATFORM=${{ matrix.arch.platform }}
            BASE_ARCH=${{ matrix.arch.base }}
          tags: |
            ghcr.io/${{ env.owner }}/openmohaa-container:latest-${{ matrix.arch.tag }}
            ghcr.io/${{ env.owner }}/openmohaa-container:${{ github.ref_name }}-${{ matrix.arch.tag }}

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
