name: Sync Upstream Source

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    name: Sync upstream to local upstream branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote and fetch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add upstream https://github.com/openmoh/openmohaa.git
          git tag -l | xargs -r git tag -d
          git fetch upstream --tags --force

      - name: Reset upstream branch and preserve workflows
        run: |
          # Save your workflows
          mkdir -p /tmp/my-workflows
          cp -r .github/workflows/* /tmp/my-workflows/ 2>/dev/null || true
          
          git checkout -B upstream upstream/main
          rm -rf .github/workflows
          mkdir -p .github/workflows
          cp -r /tmp/my-workflows/* .github/workflows/ 2>/dev/null || true
          
          git add .
          git commit -m "Sync upstream, preserve local workflows" || true
          git push origin upstream --force

      - name: Wipe existing remote tags
        run: |
          # delete LOCAL tags
          git tag -l | xargs -r git tag -d
      
          # delete REMOTE tags
          git ls-remote --tags origin \
            | awk '{print $2}' \
            | sed 's#refs/tags/##' \
            | xargs -r -n1 git push origin --delete
      
          # refetch upstream tags (with dates)
          git fetch upstream "+refs/tags/*:refs/tags/*" --tags --force
    
      - name: Create clean tags without upstream workflows (preserve dates)
        run: |
          mkdir -p /tmp/my-workflows
          cp -r .github/workflows/* /tmp/my-workflows/ 2>/dev/null || true
      
          for tag in $(git tag -l); do
            echo "Processing tag: $tag"
            # 1) Get original tagger date
            orig_date=$(git for-each-ref \
              --format='%(taggerdate:iso8601)' \
              refs/tags/"$tag")
      
            # 2) Branch off the tag
            git checkout -B temp-"$tag" "$tag"
      
            # 3) Remove upstream workflows, re‑add yours
            rm -rf .github/workflows
            mkdir -p .github/workflows
            cp -r /tmp/my-workflows/* .github/workflows/ 2>/dev/null || true
      
            # 4) Commit the cleanup, preserving the commit date of the tagged commit
            git add .github/workflows
            git commit -m "Remove upstream workflows from $tag" \
              --date="$(git show -s --format=%cI "$tag")"
      
            # 5) Re‑tag as annotated, *preserving the tagger date* via GIT_COMMITTER_DATE
            GIT_COMMITTER_DATE="$orig_date" \
            git tag -a "$tag" -m "Cleaned tag $tag" --force
      
            # 6) Switch back and delete temp branch
            git checkout upstream
            git branch -D temp-"$tag"
          done
      
          # 7) Push all rewritten tags
          git push origin --tags --force


