name: Sync Upstream Source

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    name: Sync upstream to local upstream branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote and fetch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add upstream https://github.com/openmoh/openmohaa.git
          git tag -l | xargs -r git tag -d
          git fetch upstream --tags --force

      - name: Reset upstream branch and preserve workflows
        run: |
          # Save your workflows
          mkdir -p /tmp/my-workflows
          cp -r .github/workflows/* /tmp/my-workflows/ 2>/dev/null || true
          
          git checkout -B upstream upstream/main
          rm -rf .github/workflows
          mkdir -p .github/workflows
          cp -r /tmp/my-workflows/* .github/workflows/ 2>/dev/null || true
          
          git add .
          git commit -m "Sync upstream, preserve local workflows" || true
          git push origin upstream --force
          
      - name: Wipe existing remote tags
        run: |
          # A) Remove every tag from *your* local clone
          git tag -l | xargs -r git tag -d
      
          # B) Remove every tag from *your* GitHub fork
          git ls-remote --tags origin \
            | awk '{print $2}' \
            | grep -v '\^{}' \
            | sed 's#refs/tags/##' \
            | xargs -r -n1 git push origin --delete
      
          # C) Re‑fetch *upstream’s* tags (so your local now has fresh upstream tags)
          git fetch upstream "+refs/tags/*:refs/tags/*" --tags --force
    
      - name: Create clean tags without upstream workflows (preserve dates)
        run: |
          # 1) Backup your workflows  
          mkdir -p /tmp/my-workflows
          cp -r .github/workflows/* /tmp/my-workflows/ 2>/dev/null || true
      
          # 2) For each upstream tag in your local repo…
          for tag in $(git tag -l); do
            echo "Rewriting $tag…"
      
            # a) Grab the tagger’s original date
            orig_date=$(git for-each-ref \
              --format='%(taggerdate:iso8601)' \
              refs/tags/"$tag")
      
            # b) Checkout a temp branch at that tag
            git checkout -B temp-"$tag" "$tag"
      
            # c) Strip upstream workflows, restore yours
            rm -rf .github/workflows
            mkdir -p .github/workflows
            cp -r /tmp/my-workflows/* .github/workflows/ 2>/dev/null || true
      
            # d) Commit the cleanup, preserving the commit’s original date
            git add .github/workflows
            git commit -m "Remove upstream workflows from $tag" \
              --date="$(git show -s --format=%cI "$tag")"
      
            # e) Recreate an *annotated* tag, forcing both dates
            GIT_COMMITTER_DATE="$orig_date" \
            GIT_TAGGER_DATE="$orig_date" \
            git tag -a "$tag" -m "Cleaned tag $tag" --force
      
            # f) Cleanup the temp branch
            git checkout upstream
            git branch -D temp-"$tag"
          done
      
          # 3) Push all your newly‑annotated tags up to GitHub
          git push origin --tags --force
